sonar.projectKey=gryphus-lab_cvbuilder
sonar.organization=gryphus-lab


sonar.projectName=cvbuilder

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**, **/*.pyc, **/results/**, **/coverage.xml

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
